CREATE DATABASE mydata;
USE mydata;

CREATE TABLE menu (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100),
    TYPE VARCHAR(50),
    PRICE DECIMAL(10,2)
);

CREATE TABLE cusdet (
    ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
    ID INT,
    QUANTITY INT,
    NAME VARCHAR(100),
    MOBNO BIGINT,
    ADDRESS VARCHAR(255),
    TOTALPRICE DECIMAL(10,2),
    FOREIGN KEY (ID) REFERENCES menu(ID)
);

CREATE TABLE feedback (
    FEEDBACK_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100),
    COMMENTS TEXT
);
